@echo off
SET GIT=C:\Program Files\Git\cmd\git.exe
echo Resetting history to remove the blocked commit...
"%GIT%" reset --hard ac2fc9d
echo Removing push_fix.bat...
del push_fix.bat 2>nul
echo Adding files...
"%GIT%" add .
echo Committing cleanly...
"%GIT%" commit -m "Fix visibility in light mode - clean push"
echo Pushing...
"%GIT%" push "https://kraa1981t:%1@github.com/kraa1981t/finalyze-ai.git" main --force
